application: chromez-app
version: 1
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: ssl
  version: latest

handlers:
- url: /redirect/.*
  script: redirect.app
- url: /
  upload: client/simple.html
  static_files: client/simple.html
- url: /bower_components/(.+\.(js|html))
  static_files: bower_components/\1
  upload: bower_components/.*
- url: /configs/(.+\.json)
  static_files: configs/\1
  upload: configs/.*
- url: /(.+\.(js|html))
  static_files: client/\1
  upload: client/.*
